version: '3.3'

services:

#------------------------User------------------------------

  user-db:
    container_name: user-db
    build: ./user/userDB
    volumes:
      - './user/userDB:/app/src'
    ports:
      - '${USER_DB_PORT}:${COUCHDB_PORT}'
    env_file:
      - '.env'

  user-init-db:
    container_name: user-init-db
    build: ./user/userDB/init_db
    command: [ "./wait-for-couchdb.sh" ]
    volumes:
      - './user/userDB/init_db:/app/src'
    depends_on: [ "user-db" ]


  user-command-service:
    container_name: user-command-service
    build: ./user/userCommand
    volumes:
      - './user/userCommand:/app/src'
    ports:
      - '${USER_COMMAND_PORT}:${HOST_PORT}'
    env_file:
      - '.env'

  user-query-service:
    container_name: user-query-service
    build: ./user/userQuery
    volumes:
      - './user/userQuery:/app/src'
    ports:
      - '${USER_QUERY_PORT}:${HOST_PORT}'
    env_file:
      - '.env'

#------------------------Actor------------------------------

  actor-db:
    container_name: actor-db
    build: ./actor/actorDB
    volumes:
      - './actor/actorDB:/app/src'
    ports:
      - '${ACTOR_DB_PORT}:${COUCHDB_PORT}'
    env_file:
      - '.env'

  actor-init-db:
    container_name: actor-init-db
    build: ./actor/actorDB/init_db
    command: [ "./wait-for-couchdb.sh" ]
    volumes:
      - './actor/actorDB/init_db:/app/src'
    depends_on: [ "actor-db" ]

  actor-command-service:
    container_name: actor-command-service
    build: ./actor/actorCommand
    volumes:
      - './actor/actorCommand:/app/src'
    ports:
      - '${ACTOR_COMMAND_PORT}:${HOST_PORT}'
    env_file:
      - '.env'

  actor-query-service:
    container_name: actor-query-service
    build: ./actor/actorQuery
    volumes:
      - './actor/actorQuery:/app/src'
    ports:
      - '${ACTOR_QUERY_PORT}:${HOST_PORT}'
    env_file:
      - '.env'

#------------------------Block------------------------------

  block-outbox-service:
    container_name : block-outbox-service
    build: ./outbox/blockOutbox
    volumes:
      - './outbox/blockOutbox:/app/src'
    ports:
      - '${BLOCK_OUTBOX_PORT}:${HOST_PORT}'
    env_file:
      - '.env'

  block-inbox-command-service:
    container_name : block-inbox-command-service
    build: ./inbox/command/blockInbox
    volumes:
      - './inbox/command/blockInbox:/app/src'
    ports:
      - '${BLOCK_INBOX_PORT}:${HOST_PORT}'
    env_file:
      - '.env'
    extra_hosts:
      - "local.wolkenkit.io:${HOST}"

  block-inbox-query-service:
    container_name : block-inbox-query-service
    build: ./inbox/databaseQuerier/blockQuerier
    volumes:
      - './inbox/databaseQuerier/blockQuerier:/app/src'
    ports:
      - '${BLOCK_QUERY_PORT}:${HOST_PORT}'
    env_file:
      - '.env'
    extra_hosts:
      - "local.wolkenkit.io:${HOST}"

#------------------------Follow------------------------------

  follow-outbox-service:
    container_name : follow-outbox-service
    build: ./outbox/followOutbox
    volumes:
      - './outbox/followOutbox:/app/src'
    env_file:
      - '.env'
    ports:
      - '${FOLLOW_OUTBOX_PORT}:${HOST_PORT}'

  follow-inbox-command-service:
    container_name : follow-inbox-command-service
    build: ./inbox/command/followInbox
    volumes:
      - './inbox/command/followInbox:/app/src'
    ports:
      - '${FOLLOW_INBOX_PORT}:${HOST_PORT}'
    env_file:
      - '.env'
    extra_hosts:
      - "local.wolkenkit.io:${HOST}"

  follow-inbox-query-service:
    container_name : follow-inbox-query-service
    build: ./inbox/databaseQuerier/followQuerier
    volumes:
      - './inbox/databaseQuerier/followQuerier:/app/src'
    ports:
      - '${FOLLOW_QUERY_PORT}:${HOST_PORT}'
    env_file:
      - '.env'
    extra_hosts:
      - "local.wolkenkit.io:${HOST}"

#------------------------Like------------------------------

  like-outbox-service:
    container_name : like-outbox-service
    build: ./outbox/likeOutbox
    volumes:
      - './outbox/likeOutbox:/app/src'
    ports:
      - '${LIKE_OUTBOX_PORT}:${HOST_PORT}'
    env_file:
      - '.env'


  like-inbox-command-service:
    container_name : like-inbox-command-service
    build: ./inbox/command/likeInbox
    volumes:
      - './inbox/command/likeInbox:/app/src'
    ports:
      - '${LIKE_INBOX_PORT}:${HOST_PORT}'
    env_file:
      - '.env'
    extra_hosts:
      - "local.wolkenkit.io:${HOST}"

  like-inbox-query-service:
    container_name : like-inbox-query-service
    build: ./inbox/databaseQuerier/likeQuerier
    volumes:
      - './inbox/databaseQuerier/likeQuerier:/app/src'
    ports:
      - '${LIKE_QUERY_PORT}:${HOST_PORT}'
    env_file:
      - '.env'
    extra_hosts:
      - "local.wolkenkit.io:${HOST}"

#------------------------Note------------------------------

  note-outbox-service:
    container_name : note-outbox-service
    build: ./outbox/noteOutbox
    volumes:
      - './outbox/noteOutbox:/app/src'
    ports:
      - '${NOTE_OUTBOX_PORT}:${HOST_PORT}'
    env_file:
      - '.env'

  note-inbox-command-service:
    container_name : note-inbox-command-service
    build: ./inbox/command/noteInbox
    volumes:
      - './inbox/command/noteInbox:/app/src'
    ports:
      - '${NOTE_INBOX_PORT}:${HOST_PORT}'
    env_file:
      - '.env'
    extra_hosts:
      - "local.wolkenkit.io:${HOST}"

  note-inbox-query-service:
    container_name : note-inbox-query-service
    build: ./inbox/databaseQuerier/noteQuerier
    volumes:
      - './inbox/databaseQuerier/noteQuerier:/app/src'
    ports:
      - '${NOTE_QUERY_PORT}:${HOST_PORT}'
    env_file:
      - '.env'
    extra_hosts:
      - "local.wolkenkit.io:${HOST}"

#------------------------Share------------------------------

  share-outbox-service:
    container_name : share-outbox-service
    build: ./outbox/shareOutbox
    volumes:
      - './outbox/shareOutbox:/app/src'
    ports:
      - '${SHARE_OUTBOX_PORT}:${HOST_PORT}'
    env_file:
      - '.env'

  share-inbox-command-service:
    container_name : share-inbox-command-service
    build: ./inbox/command/shareInbox
    volumes:
      - './inbox/command/shareInbox:/app/src'
    ports:
      - '${SHARE_INBOX_PORT}:${HOST_PORT}'
    env_file:
      - '.env'
    extra_hosts:
      - "local.wolkenkit.io:${HOST}"

  share-inbox-query-service:
    container_name : share-inbox-query-service
    build: ./inbox/databaseQuerier/shareQuerier
    volumes:
      - './inbox/databaseQuerier/shareQuerier:/app/src'
    ports:
      - '${SHARE_QUERY_PORT}:${HOST_PORT}'
    env_file:
      - '.env'
    extra_hosts:
      - "local.wolkenkit.io:${HOST}"





